version: '3.8'

services:
  llmpostor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7650:8000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=change-this-in-production
      - PORT=8000
      - PROMPTS_FILE=/app/prompts.yaml
      - LOG_LEVEL=info
      - RESPONSE_TIME_LIMIT=180
      - GUESSING_TIME_LIMIT=120
      - RESULTS_DISPLAY_TIME=30
      - MAX_PLAYERS_PER_ROOM=8
      - MAX_RESPONSE_LENGTH=100

      - DOCKER_BUILDKIT=0
      - COMPOSE_DOCKER_CLI_BUILD=0
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
